#pragma once

#include "WPILib.h"
#include <math.h>
class OI {
<<<<<<< HEAD
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* driverJoystickLeft;
	Joystick* driverJoystickRight;
	JoystickButton* a;
	JoystickButton* b;
	JoystickButton* xb;
	JoystickButton* y;
	JoystickButton* lb;
	JoystickButton* rb;
	JoystickButton* back;
	JoystickButton* start;
	JoystickButton* ljoy;
	JoystickButton* rjoy;
	//^Xbox^
	JoystickButton* xp;
	JoystickButton* circle;
	JoystickButton* tri;
	JoystickButton* sq; //square
	JoystickButton* r1;
	JoystickButton* l1;
	JoystickButton* r2;
	JoystickButton* l2;
	JoystickButton* r3;
	JoystickButton* l3;
	JoystickButton* pad; //touchpad
	JoystickButton* shr; //share
	JoystickButton* opt; //options
	JoystickButton* ps; //PS button
	//^PS4^

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
=======
  private:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Joystick* xBoxControl;
    Joystick* xBoxDrive;
    JoystickButton* DriveA;
    JoystickButton* DriveB;
    JoystickButton* DriveX;
    JoystickButton* DriveY;
    JoystickButton* DriveLB;
    JoystickButton* DriveRB;
    JoystickButton* DriveBack;
    JoystickButton* DriveStart;
    JoystickButton* ljoy;
    JoystickButton* rjoy;
    JoystickButton* DriveLeftStick;
    JoystickButton* DriveRightStick;
    // Xbox Drive ^^^
    JoystickButton* ControlA;
    JoystickButton* ControlB;
    JoystickButton* ControlX;
    JoystickButton* ControlY;
    JoystickButton* ControlLB;
    JoystickButton* ControlRB;
    JoystickButton* ControlBack;
    JoystickButton* ControlStart;

    JoystickButton* ControlLeftStick;
    JoystickButton* ControlRightStick;
    // Xbox Control ^^^

    double adjustJoystick(double);
>>>>>>> 2049c4a3761c73539323a05bf768cbdc00da8cff

  public:
    OI();

<<<<<<< HEAD
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	Joystick* getDriverJoystickRight();
	Joystick* getDriverJoystickLeft();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	double getJoystickMagnitude();
	double getJoystickZ();
	double getJoystickX();
	double getJoystickY();
	double getPS4Joy();
	bool getL1();
};
#endif
=======
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
    Joystick* getControlJoystick();
    Joystick* getDriveJoystick();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
    double getJoystickMagnitude();
    double getDriveRightX();
    double getDriveLeftX();
    double getDriveLeftY();
    double getControlJoy();
    bool getLB();
};
>>>>>>> 2049c4a3761c73539323a05bf768cbdc00da8cff
