// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
#include <math.h>
class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* xBoxControl;
	Joystick* xBoxDrive;
	JoystickButton* DriveA;
	JoystickButton* DriveB;
	JoystickButton* DriveX;
	JoystickButton* DriveY;
	JoystickButton* DriveLB;
	JoystickButton* DriveRB;
	JoystickButton* DriveBack;
	JoystickButton* DriveStart;
	JoystickButton* ljoy;
	JoystickButton* rjoy;
	//Xbox Drive ^^^
	JoystickButton* ControlA;
	JoystickButton* ControlB;
	JoystickButton* ControlX;
	JoystickButton* ControlY;
	JoystickButton* ControlLB;
	JoystickButton* ControlRB;
	JoystickButton* ControlBack;
	JoystickButton* ControlStart;
	//Xbox Control ^^^

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	double pi;
	double adjustJoystick(double);
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	Joystick* getControlJoystick();
	Joystick* getDriveJoystick();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	double getJoystickMagnitude();
	double getJoystickZ();
	double getJoystickX();
	double getJoystickY();
	double getControlJoy();
	bool getLB();
};
#endif
