// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include <math.h>
#include "ctre/Phoenix.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class DriveTrain: public Subsystem {
private:
	static constexpr double pi=3.14159;
	void SetSteerSetpoint(float FLSet, float FRSet, float RLSet, float RRSet);
	void SetDriveSpeed(float FLSpeed, float FRSpeed, float RLSpeed, float RRSpeed);
	
	//DriveDirection
	bool driveFront;
	
	//Steering Variables	
	double radian; // input steering angle in radians
	double A;	//A is the ratio of X to turn harder 
	double W;	//W is the distance form the mid-point of one back wheel to the mid-point of the other back wheel
	double X;	//X is the distance form the mid-point of the back wheels to the mid-point of the front wheels 
	double Y;	//Y is the distance from the mid-point of one front wheel to the mid-point of the other font wheel
	
	double FL;	//FL, distance from Front Left Wheel to the center of rotation
	double FR;	//FR, distance from Front Right Wheel to the center of rotation
	double RL;	//RL, distance from Rear Left Wheel to the center of rotation
	double RR;	//RR, distance from Rear Right Wheel to the center of rotation
	

	double FRRatio;	//Ratio of Speed of Front Right wheel
	double FLRatio;	//Ratio of Speed of Front Left wheel
	double RRRatio;	//Ratio of Speed of Rear Right wheel
	double RLRatio;	//Ratio of Speed of Rear Left wheel
	
	double FLOffset;
	double FROffset;
	double RLOffset;
	double RROffset;
	
	//Crab Variables
	double AP;
	double BP;
	double CP;
	double DP;
	double radius; //distance from center to each wheel
	
	int FLInv;
	int FRInv;
	int RLInv;
	int RRInv;
		
	double CorrectSteerSetpoint(double setpoint);


public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	WPI_TalonSRX* frontLeftDrive;
	WPI_TalonSRX* frontRightDrive;
	WPI_TalonSRX* rearLeftDrive;
	WPI_TalonSRX* rearRightDrive;
	AnalogInput* frontLeftPos;
	WPI_TalonSRX* frontLeftSteer;
	PIDController* frontLeft;
	AnalogInput* frontRightPos;
	WPI_TalonSRX* frontRightSteer;
	PIDController* frontRight;
	AnalogInput* rearLeftPos;
	WPI_TalonSRX* rearLeftSteer;
	PIDController* rearLeft;
	AnalogInput* rearRightPos;
	WPI_TalonSRX* rearRightSteer;
	PIDController* rearRight;

	PIDController* gyroPID;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DriveTrain();
	void InitDefaultCommand();
	void TwistRight();
	void TwistLeft();
	void SetWheelbase(float w, float x, float y);
	void SetOffsets(double FLOff, double FROff, double RLOff, double RROff);
	void Crab(float twist, float y, float x, bool useGyro);
	void Lock();
	void Test();
	void ToggleFrontBack();
	void DriveForward();
	void DriveReverse();
	void Stop();

};
#endif
